### ISSUE TITLE
   Bug: jasmineNodeOpts: should be jasmineOpts: to allow  "defaultTimeoutInterval" to be active

### ISSUE THREAD

**Issue by darkartswizard** [webdriverio/jasmine-boilerplate#602]
jasmineNodeOpts: {
        // Jasmine default timeout
        defaultTimeoutInterval: 60000,
}

Leaves the timeout at default 10 seconds, not 1 minute, generating this message for any test over ten seconds. 
**Error: Timeout - Async function did not complete within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)**

Probable cause for this error:
**Error: Couldn't find page handle error.** 
when commands are sent against the browser after it's been closed.

Change to jasmineOpts: to allow Jasmine to execute tests longer than 10 seconds 
```
    jasmineOpts: {
        // Jasmine default timeout
        defaultTimeoutInterval: 60000,
}
```

**Comment by christian-bromann** [comment]
Thanks for pointing out the bug. I pushed a commit with a fix. Feel free to raise PRs with easy bug fixes like this yourself. If there are any issues with that, let me know!

**Comment by darkartswizard** [comment]
I tried the PR first but it gave me some blocking error, so I figured I'd write the ticket instead.
I just did another PR with my branch and saw this message.
I closed the duplicate PR and will delete my branch.

**Comment by christian-bromann** [comment]
> it gave me some blocking error

What was the blocking error?
