### ISSUE TITLE
Broken type recognition for 'describe'

### ISSUE THREAD

**Issue by vivacenontroppo** [webdriverio/jasmine-boilerplate#635]
**Steps to reproduce:**

1. Clone the project
2. Open on the main branch
3. Use npm install

**Result:**

Typescript error on each 'describe':
`
Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and then add 'jest' or 'mocha' to the types field in your tsconfig.
`

The funny thing is I have built a project based on that boilerplate and solved that problem, but now I can not reproduce the fix that I wanted to introduce here, that's why I am raising this.
Edit: Adding @types/jasmine to dependencies solves the issue but I guess that's not the way to go...

**Comment by christian-bromann** [comment]
> Adding @types/jasmine to dependencies solves the issue but I guess that's not the way to go...

It is the way to go.

**Comment by vivacenontroppo** [comment]
Oh ok, I though there is something I’m missing because the fix seemed to obvious. Thanks.
